apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testdeployment
  name: bookapiserverdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: rudro25/bookapiserver
          name: test
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP